on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: derekmaeshiro/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - run: make format && git diff
      - run: make cppcheck
      - run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc make HW=NSUMO
      - run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc make HW=LAUNCHPAD
      - run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc tools/build_tests.sh

