on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: derekmaeshiro/msp430-gcc-9.3.1.11:banana
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - run: make format && git diff --quiet
      - run: make
      - run: make cppcheck
